version: '2.3'
services:
        trim:
               build:
                       context: .
                       dockerfile: ./trim/Dockerfile
               image: icon/trim
               container_name: trim
               ports:
                       - 127.0.0.1:11112:8888
               volumes:
                       - ./input:/input
                       - ./output:/output
                       - ./faces:/faces

        crip:
                build:
                        context: .
                        dockerfile: ./crip/Dockerfile
                image: icon/crip
                container_name: crip
                volumes:
                        - ./output:/output
                        - ./input:/input
                runtime: nvidia
                environment:
                        - NVIDIA_VISIBLE_DEVICES=all
                        - NVIDIA_DRIVER_CAPABILITIES=all
        
        style:
                build:
                        context: .
                        dockerfile: ./style/Dockerfile
                image: icon/style
                container_name: style
                tty: true
                volumes:
                        - ./faces:/faces
                        - ./datasets:/datasets
                        - ./results:/results

                runtime: nvidia
                environment:
                        - NVIDIA_VISIBLE_DEVICES=all
                        - NVIDIA_DRIVER_CAPABILITIES=all
